name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        python: ["py37", "py38", "py39", "py310"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build

    - name: Build wheels
      run: python setup.py bdist_wheel --python-tag ${{ matrix.python }}

    - name: Upload wheels
      env:
        TWINE_USERNAME: "fortefrankie"
        TWINE_PASSWORD: "Take1la$tdrag"
      run: |
        twine upload dist/*